### ISSUE TITLE
Last item of array not working

### ISSUE THREAD

**Issue by jordanyoungs** [Galbar/JsonPath-PHP#27] opened 2019-05-15 15:18 UTC
I've been trying to use different notations to get the last item in an array of objects. It seems that the '-' character is breaking the code:

`$.Line[-1:].Amount  --> error: Invalid JSON path expression. The error is around character position 7`

`$.Line[-1].Amount  --> error: Invalid JSON path expression. The error is around character position 7`

`$.Line[0].Amount  --> successfully returns the Amount of the first object in the Line array`

**Comment by Galbar** [comment] 2019-05-15 15:38
Hi @jordanyoungs! Thank you for reporting this. Sadly I'm unable to reproduce it.

I've created a test: https://gist.github.com/Galbar/9dae20c001a98f9efcdff384ea80dd09
Then I tried querying it with your example query:  
```
php issue27-example.php '$.Line[-1].Amount'
```
The result is the expected:
```
[0]
```
I also tried with `[-1:]` and got the same result.

Could you please provide an example that reproduces it?

**Comment by jordanyoungs** [comment] 2019-05-15 19:17
Thanks for the quick response! I am able to get that gist working too, so there must be something wrong with my project. Thanks for the help

**Comment by jordanyoungs** [comment] 2019-05-16 14:44
I figured out what was going on. Long story short this particular piece of code was using jsonpath in a mysql query, which means the error was coming from mysql, which has different json path syntax! My project uses this library in many other parts so my initial reaction was that it must be coming from here, whoops.

**Comment by Galbar** [comment] 2019-05-18 10:13
Cool that you figured it out!
I'll close the issue now

**Closed by Galbar** 2019-05-18 10:13 UTC
