### ISSUE TITLE
Bug when using negative index triggers DivisionByZeroError

### ISSUE THREAD

**Issue by kohlerdominik** [Galbar/JsonPath-PHP#60] opened 2022-07-29 10:52 UTC
Hi
I'm just stumbled across a bug when using negative index, but the element with this index does not exist.
The error can be triggered like this:

```php
$object = new \JsonPath\JsonObject('{"data": []}');
$result = $object->get('$.data[-1]');
// Triggers DivisionByZeroError
```

When less objects are present than the negative index, it does overflow, and this seems strange to me. But at least it does not trigger an Error. This might be a secondary bug:
```php
$object = new \JsonPath\JsonObject('{"data": [{"id": 1},{"id": 2}]}');
$result = $object->get('$.data[-5].id');
// $result is [2]
```

In case index is less than the size of the object, everything works as intended.
```php
$object = new \JsonPath\JsonObject('{"data": [{"id": 1}]}');
$result = $object->get('$.data[-1].id');
// $result is [1]

$object = new \JsonPath\JsonObject('{"data": [{"id": 1},{"id": 2}]}');
$result = $object->get('$.data[-1].id');
// $result is [2]
```

The bug does not apear with positive index, which does not exist. Also this behaviour does make more sense to me than the one with negative index that does not exist:
```php
$object = new \JsonPath\JsonObject('{"data": []}');
$result = $object->get('$.data[1].id');
// $result is []

$object = new \JsonPath\JsonObject('{"data": [{"id": 1},{"id": 2}]}');
$result = $object->get('$.data[3].id');$
// $result is []
```

**Comment by Galbar** [comment] 2022-07-29 12:09
Hi @kohlerdominik,

Thanks for reporting the bug!

I had a quick look at the code and my guess would be that it is caused by the mod operation (`%`) in this part of the code: https://github.com/Galbar/JsonPath-PHP/blob/eab3a7e97d1bcf23b77df87c5ada241789b17c79/src/Galbar/JsonPath/Expression/IndexList.php#L24-L37

It would seem that by adding an early exit to that method if the array (`$partial`) is empty would fix it. I'll get to it when I have some time (summer is complicated).

**Comment by kohlerdominik** [comment] 2022-07-31 09:18
Hi @Galbar 

Yes, the early return would fix this I guess. However, why is the mod there in the first place? When I'm quering non-existing negative index with the most starred JsonPath implementation in Github, which is [json-path/JsonPath](https://github.com/json-path/JsonPath), it returns an empty result instead of overflowing. For me personally, this behaviour makes a lot more sense than the current implementation here.

There's a JsonPath evaluator using this library available here. I preconfigured the path already: [jsonpath.herokuapp.com/?path=$..book[-5]](jsonpath.herokuapp.com/?path=$..book[-5]) → returns empty result

So is it an option for you to adjust the behaviour by removing this section entierly, whichs seems to be only there to add the overflowing?
```php
        $indexes = array_map(
            function($i) use ($partial) {
                if ($i < 0) {
                    $n = count($partial);
                    $i = $i % $n;
                    if ($i < 0) {
                        $i += $n;
                    }
                }
                return $i;
            },
            $indexes
        );
```
Unfortunately, there's not git history on this, so I can't retrace why it was added.

**Comment by Galbar** [comment] 2022-08-01 15:04
It is implemented because the original JsonPath specification explicitly defines it: https://goessner.net/articles/JsonPath/
![image](https://user-images.githubusercontent.com/3595851/182179844-fc32bb05-95aa-4d88-9370-45203840106b.png)

**Comment by kohlerdominik** [comment] 2022-08-31 14:05
Hi Galbar

I totally missed your response, sorry about that!

I am sorry that I have to disagree. Neiter can I see that the specification tells, that negative index should do overflow. 
Also when using this expression with Goessner Jsonpath Implementation, it returns false rather than `2` in this implementation:
![grafik](https://user-images.githubusercontent.com/18621527/187697985-8963bba5-dd2e-48e5-a3c8-6cd46b3aea55.png)
https://jsonpath.curiousconcept.com/

**Comment by Galbar** [comment] 2022-09-01 20:07
oh, I think I had misunderstood. The problem is that if you have an array of size 5, when using indexes below -4 it wraps around instead of returning "not found".

Is my understanding now correct?

If that is the case, then that would be a bug present since the beginning and it would "break" backwards compatibility. It does make sense to fix it, though.

**Comment by kohlerdominik** [comment] 2022-09-02 15:09
Hi Galbar

Yes exactly, that's what I meant. The bug with the "DivisionByZeroError" only existed, because of this extra implementation that it does wrap if negative index is less than max size. But this wrap is unspecified and also unseen in other implementations, therefore it seems very curious to me, that it exists in the first place.

**Comment by cburgmer** [comment] 2022-09-13 08:51
Just to call out, this issue was also found in the comparison project earlier: https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/PHP_galbar-jsonpath.md

Let me know if more visibility could help this project here.

**Comment by Galbar** [comment] 2023-03-01 18:14
I believe the issue is fixed in the referenced commit. If that is not the case, please feel free to reopen and document what is missing. Cheers!

**Closed** 2023-03-01 18:14 UTC
