### ISSUE TITLE
Querying the literal key "length"? 

### ISSUE THREAD

**Issue by ShaneOH** [Galbar/JsonPath-PHP#62] opened 2022-08-04 17:49 UTC
Hey @Galbar !'ve encountered an interesting issue here, we have the following example JSON:

```
{"box": {"length":[{"locale":null,"scope":null,"data":{"amount":"130.0000","unit":"CENTIMETER"}}]
```

We want to query with the following: `$.box.length.*.data.amount`

But it looks like that is conflicting with the actual _function_ `.length`, and we're hitting this Exception:

```
[04-Aug-2022 16:07:43 UTC] UNCAUGHT EXCEPTION | PID: 112341 | TYPE: TypeError | CODE: 0 | MESSAGE: count(): Argument #1 ($value) must be of type Countable|array, int given | FILE: /var/sdapp/suredone/vendor/galbar/jsonpath/src/Galbar/JsonPath/JsonPath.php | LINE: 40 | TRACE: #0 /var/sdapp/suredone/vendor/galbar/jsonpath/src/Galbar/JsonPath/JsonPath.php(40): count()
#1 /var/sdapp/suredone/vendor/galbar/jsonpath/src/Galbar/JsonPath/JsonPath.php(28): JsonPath\JsonPath::subtreeGet()
#2 /var/sdapp/suredone/vendor/galbar/jsonpath/src/Galbar/JsonPath/JsonObject.php(221): JsonPath\JsonPath::get()
```

Is there any way around this? How can we query on the _key_ of `"length"` rather than calling the _function_ `.length`?

**Comment by Galbar** [comment] 2022-08-18 10:30
Hi @ShaneOH, I have tried to reproduce your problem but I was unable to get the error you are seeing.

As you can see, I added a new test in https://github.com/Galbar/JsonPath-PHP/commit/5e4f1f83649bf19ed5f8bdb830c11150650c9252 with the same test case you provide. That commit passes all tests, as you can see in the [corresponding pipeline](https://github.com/Galbar/JsonPath-PHP/runs/7896570850).

Looking a bit deeper, it would look like an unexpected value type was assigned to a variable that is passed to a `count()`. That variable, `$selection`, is either `false` (and immediately exists the loop) or it is an `array()` because that is what it is assigned to at the end of the loop.

I don't know how you got that error. If you could provide a minimum reproducible case that would be awesome.

**Closed** 2022-11-17 21:55 UTC
